import { defineJoinerConfig } from "@medusajs/framework/utils"
import { EventModule } from "."

export const joinerConfig = defineJoinerConfig(EventModule, {
  linkableKeys: {
    // Merged with the autogenerated ones to maintain backward compatibility
    publishable_key_id: "EventWebhook",
  },
})
